"""empty message

Revision ID: 0af48b2b9540
Revises: 98871a0b9147
Create Date: 2024-03-16 23:04:18.528445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0af48b2b9540'
down_revision = '98871a0b9147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.alter_column('bedrooms',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_listing', schema=None) as batch_op:
        batch_op.alter_column('bathrooms',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('bedrooms',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
